language: node_js
node_js:
  - "10"
  - "11"

before_install:
  - npm install codecov -g

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
 
script:
  - tsc

after_success:
  - codecov

services:
  - postgresql