language: node_js
node_js:
  - "10"
  - "11"

before_install:
  - npm install codecov -g

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE DATABASE test_db_2;" -U postgres
 
script:
  - tsc
  - npm test

before_deploy:
  - tsc

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  tag: next
  on:
    tags: true

after_success:
  - codecov

services:
  - postgresql